services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    image: auth-service:latest
    env_file:
      - postgres.env
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: postgres:16.1
    container_name: postservice-postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432