spring:
  application:
    name: PostService
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver
    hikari:  # ????????? ???? ?????????? HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: false  # ????????? ??????? ???????? ??? ??????????
    open-in-view: false  # ????????? Open Session in View ??? ????????? ??????? ? ??????? ?????????
  data:
    jpa:
      repositories:
        enabled: true