spring:
  application:
    name: PostService

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # create | create-drop | update | validate | none
    show-sql: true            # ?????????? SQL ? ???????
    properties:
      hibernate:
        format_sql: true      # ????????????? SQL ? ???????
        dialect: org.hibernate.dialect.PostgreSQLDialect

    #open-in-view: false       # ????? ?????????, ????? ???????? ??????? ???????? ? ???-????
