spring:
  config:
    import: optional:file:environment/dev.env[.properties]

  application:
    name: PostService

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: false
    open-in-view: false

  data:
    jpa:
      repositories:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID_OAUTH2}
            client-secret: ${GITHUB_SECRET_OAUTH2}
            scope:
              - user:email

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 6000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

app:
  version: ${project.version}

jwt:
  access-token-key: ${JWT_ACCESS_KEY}
  refresh-token-key: ${JWT_REFRESH_KEY}