name: Build and Deploy with Dockerfile

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t auth-service:latest .

      - name: Save Docker image to tarball
        run: |
          docker save auth-service:latest -o auth-service.tar

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy image to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" auth-service.tar spaxer@${{ secrets.SSH_HOST }}:/home/spaxer/application/AuthService/

      - name: Load image and run compose
        run: |
          ssh -i ~/.ssh/id_rsa spaxer@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/spaxer/application/AuthService
            docker load -i auth-service.tar
            docker compose up -d --build
          EOF
