name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: maven
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: develop
          repo-url: ${{ github.repository }}
